### ISSUE TITLE
Error while navigating the package

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/objectscript-visual-editor#1]
![image](https://github.com/intersystems-community/objectscript-visual-editor/assets/18187317/5665abf5-ee84-48b0-b749-e1cbcf03879f)

index.js:3 /VisualEditor/Informer/list?ns=%25SYS&level=%25ZPM {
	"errors":[ {
			"code":5002,
			"domain":"%ObjectErrors",
			"error":"ОШИБКА #5002: Ошибка: <PRIVATE PROPERTY>GetMemberData+10^VisualEditor.REST.Informer.1",
			"id":"ObjectScriptError",
			"params":["<PRIVATE PROPERTY>GetMemberData+10^VisualEditor.REST.Informer.1"
			]
		}
	],
	"summary":"ОШИБКА #5002: Ошибка: <PRIVATE PROPERTY>GetMemberData+10^VisualEditor.REST.Informer.1"
}, 500: Internal Server Error

**Comment by SergeyMi37** [comment]
w $zv
IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2023.1 (Build 229U) Fri Apr 14 2023 17:37:52 EDT

**Comment by nikitaeverywhere** [comment]
Thanks for the report!

This thing wasn't updated since, I guess, 2019. Any contributions to the codebase with fixes are very welcome! I'm not maintaining InterSystems projects nowadays.

**Comment by nikitaeverywhere** [comment]
@SergeyMi37 I've got this from OEX team:

<img width="571" alt="image" src="https://github.com/intersystems-community/objectscript-visual-editor/assets/4989256/a4f90d02-6e66-4372-8521-0a4df459e5e7">

Any chance you can help with getting the newest XML if you're using this tool? You can just export it from IRIS with your fix
